In [1]:
import pandas as pd
s=pd.Series([10,20,30,10],index=[10,11,12,13])
#we can directly pass the index in series as per our need
#also we can pass index with the help of dictionary
q=pd.Series({'a':1,"b":2})
print(s.values)
s.index

#to check size of series
q.size
#to calculate mean
print(s.mean())

#to calculate max
s.max()

#to calculate min
s.min()

#to calculate standard deviation
s.std()

#to sum alll values
s.sum()

#to count the frequency
s.value_counts()

[10 20 30 10]
17.5

10    2
20    1
30    1
Name: count, dtype: int64

In [2]:
#collection of series is termed as  dataframe

a=pd.DataFrame([1,2],[3,4])
type(a)

pandas.DataFrame

In [3]:
pd.DataFrame({'A':[1,2],'B':[3,4]})

   A  B
0  1  3
1  2  4

In [4]:
#Load data
df=pd.read_csv('WineQT.csv')
#to get data from staring
df.head()
#to get data from end
df.tail(3)

#to get random record
df.sample(5, ignore_index=True)

#To check dimension of the dataframe
df.ndim

#to check size of data
df.size

#To get column name
df.columns

#To get basic info of data
df.info()

#to get description of the data
df.describe(include="all")

<class 'pandas.DataFrame'>
RangeIndex: 1143 entries, 0 to 1142
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   fixed acidity         1143 non-null   float64
 1   volatile acidity      1143 non-null   float64
 2   citric acid           1143 non-null   float64
 3   residual sugar        1143 non-null   float64
 4   chlorides             1143 non-null   float64
 5   free sulfur dioxide   1143 non-null   float64
 6   total sulfur dioxide  1143 non-null   float64
 7   density               1143 non-null   float64
 8   pH                    1143 non-null   float64
 9   sulphates             1143 non-null   float64
 10  alcohol               1143 non-null   float64
 11  quality               1143 non-null   int64
 12  Id                    1143 non-null   int64
dtypes: float64(11), int64(2)
memory usage: 116.2 KB

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Id
count,1143.000000,1143.000000,1143.000000,1143.000000,1143.000000,1143.000000,1143.000000,1143.000000,1143.000000,1143.000000,1143.000000,1143.000000,1143.000000
mean,8.311111,0.531339,0.268364,2.532152,0.086933,15.615486,45.914698,0.996730,3.311015,0.657708,10.442111,5.657043,804.969379
std,1.747595,0.179633,0.196686,1.355917,0.047267,10.250486,32.782130,0.001925,0.156664,0.170399,1.082196,0.805824,463.997116
min,4.600000,0.120000,0.000000,0.900000,0.012000,1.000000,6.000000,0.990070,2.740000,0.330000,8.400000,3.000000,0.000000
25%,7.100000,0.392500,0.090000,1.900000,0.070000,7.000000,21.000000,0.995570,3.205000,0.550000,9.500000,5.000000,411.000000
50%,7.900000,0.520000,0.250000,2.200000,0.079000,13.000000,37.000000,0.996680,3.310000,0.620000,10.200000,6.000000,794.000000
75%,9.100000,0.640000,0.420000,2.600000,0.090000,21.000000,61.000000,0.997845,3.400000,0.730000,11.100000,6.000000,1209.500000
max,15.900000,1.580000,1.000000,15.500000,0.611000,68.000000,289.000000,1.003690,4.010000,2.000000,14.900000,8.000000,1597.000000

In [5]:
df.describe(include='int')

           quality           Id
count  1143.000000  1143.000000
mean      5.657043   804.969379
std       0.805824   463.997116
min       3.000000     0.000000
25%       5.000000   411.000000
50%       6.000000   794.000000
75%       6.000000  1209.500000
max       8.000000  1597.000000

In [6]:
# Data Types Handling
df.dtypes

fixed acidity           float64
volatile acidity        float64
citric acid             float64
residual sugar          float64
chlorides               float64
free sulfur dioxide     float64
total sulfur dioxide    float64
density                 float64
pH                      float64
sulphates               float64
alcohol                 float64
quality                   int64
Id                        int64
dtype: object

In [7]:
df.alcohol.dtype

df['fixed acidity'].dtype

#to select the data that is of only integer datatype
df.select_dtypes(include='int').columns

#indexing and selection

df.iloc[0:2,0:4]

   fixed acidity  volatile acidity  citric acid  residual sugar
0            7.4              0.70          0.0             1.9
1            7.8              0.88          0.0             2.6

In [8]:
df['fixed acidity'][0]

df.iat[0,1]

np.float64(0.7)

In [9]:
#misssing value
df.isnull().sum()

fixed acidity           0
volatile acidity        0
citric acid             0
residual sugar          0
chlorides               0
free sulfur dioxide     0
total sulfur dioxide    0
density                 0
pH                      0
sulphates               0
alcohol                 0
quality                 0
Id                      0
dtype: int64

In [10]:
df.notnull().sum()

fixed acidity           1143
volatile acidity        1143
citric acid             1143
residual sugar          1143
chlorides               1143
free sulfur dioxide     1143
total sulfur dioxide    1143
density                 1143
pH                      1143
sulphates               1143
alcohol                 1143
quality                 1143
Id                      1143
dtype: int64

In [11]:
#to drop null data
df.dropna

#to fill null value
df.fillna(0)

#Duplicated data
df.duplicated().sum() 

#remove duplicate data
df.drop_duplicates(inplace=True)

#another way
df=df.drop_duplicates()

#to sort values
df.sort_values(by='alcohol')

df.sample(5,ignore_index=True).sort_index(ascending=False)

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Id
4,6.1,0.32,0.25,1.8,0.086,5.0,32.0,0.99464,3.36,0.44,10.1,5,1355
3,7.9,0.34,0.42,2.0,0.086,8.0,19.0,0.99546,3.35,0.60,11.4,6,1091
2,7.2,0.66,0.03,2.3,0.078,16.0,86.0,0.99743,3.53,0.57,9.7,5,891
1,11.2,0.67,0.55,2.3,0.084,6.0,13.0,1.00000,3.17,0.71,9.5,6,507
0,7.8,0.48,0.68,1.7,0.415,14.0,32.0,0.99656,3.09,1.06,9.1,6,754

In [12]:
df.sample(5).reset_index(drop=True)

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Id
0,12.0,0.37,0.76,4.2,0.066,7.0,38.0,1.00040,3.22,0.60,13.0,7,395
1,8.0,0.50,0.39,2.6,0.082,12.0,46.0,0.99850,3.43,0.62,10.7,6,1404
2,10.3,0.50,0.42,2.0,0.069,21.0,51.0,0.99820,3.16,0.72,11.5,6,466
3,10.0,0.59,0.31,2.2,0.090,26.0,62.0,0.99940,3.18,0.63,10.2,6,511
4,9.2,0.46,0.23,2.6,0.091,18.0,77.0,0.99922,3.15,0.51,9.4,5,1225

In [13]:
df.corr()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Id
fixed acidity,1.000000,-0.250728,0.673157,0.171831,0.107889,-0.164831,-0.110628,0.681501,-0.685163,0.174592,-0.075055,0.121970,-0.275826
volatile acidity,-0.250728,1.000000,-0.544187,-0.005751,0.056336,-0.001962,0.077748,0.016512,0.221492,-0.276079,-0.203909,-0.407394,-0.007892
citric acid,0.673157,-0.544187,1.000000,0.175815,0.245312,-0.057589,0.036871,0.375243,-0.546339,0.331232,0.106250,0.240821,-0.139011
residual sugar,0.171831,-0.005751,0.175815,1.000000,0.070863,0.165339,0.190790,0.380147,-0.116959,0.017475,0.058421,0.022002,-0.046344
chlorides,0.107889,0.056336,0.245312,0.070863,1.000000,0.015280,0.048163,0.208901,-0.277759,0.374784,-0.229917,-0.124085,-0.088099
free sulfur dioxide,-0.164831,-0.001962,-0.057589,0.165339,0.015280,1.000000,0.661093,-0.054150,0.072804,0.034445,-0.047095,-0.063260,0.095268
total sulfur dioxide,-0.110628,0.077748,0.036871,0.190790,0.048163,0.661093,1.000000,0.050175,-0.059126,0.026894,-0.188165,-0.183339,-0.107389
density,0.681501,0.016512,0.375243,0.380147,0.208901,-0.054150,0.050175,1.000000,-0.352775,0.143139,-0.494727,-0.175208,-0.363926
pH,-0.685163,0.221492,-0.546339,-0.116959,-0.277759,0.072804,-0.059126,-0.352775,1.000000,-0.185499,0.225322,-0.052453,0.132904
sulphates,0.174592,-0.276079,0.331232,0.017475,0.374784,0.034445,0.026894,0.143139,-0.185499,1.000000,0.094421,0.257710,-0.103954
alcohol,-0.075055,-0.203909,0.106250,0.058421,-0.229917,-0.047095,-0.188165,-0.494727,0.225322,0.094421,1.000000,0.484866,0.238087
quality,0.121970,-0.407394,0.240821,0.022002,-0.124085,-0.063260,-0.183339,-0.175208,-0.052453,0.257710,0.484866,1.000000,0.069708
Id,-0.275826,-0.007892,-0.139011,-0.046344,-0.088099,0.095268,-0.107389,-0.363926,0.132904,-0.103954,0.238087,0.069708,1.000000

In [14]:
df.quality.unique()

df['fixed acidity'].unique()

df.quality.value_counts()

quality
5    483
6    462
7    143
4     33
8     16
3      6
Name: count, dtype: int64

In [15]:
df[df['quality'] > 5]

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Id
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.99800,3.16,0.58,9.8,6,3
7,7.3,0.65,0.00,1.2,0.065,15.0,21.0,0.99460,3.39,0.47,10.0,7,7
8,7.8,0.58,0.02,2.0,0.073,9.0,18.0,0.99680,3.36,0.57,9.5,7,8
12,8.5,0.28,0.56,1.8,0.092,35.0,103.0,0.99690,3.30,0.75,10.5,7,16
13,7.9,0.32,0.51,1.8,0.341,17.0,56.0,0.99690,3.04,1.08,9.2,6,19
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1136,6.3,0.55,0.15,1.8,0.077,26.0,35.0,0.99314,3.32,0.82,11.6,6,1590
1137,5.4,0.74,0.09,1.7,0.089,16.0,26.0,0.99402,3.67,0.56,11.6,6,1591
1138,6.3,0.51,0.13,2.3,0.076,29.0,40.0,0.99574,3.42,0.75,11.0,6,1592
1139,6.8,0.62,0.08,1.9,0.068,28.0,38.0,0.99651,3.42,0.82,9.5,6,1593
1141,5.9,0.55,0.10,2.2,0.062,39.0,51.0,0.99512,3.52,0.76,11.2,6,1595

In [16]:
df.alcohol*=2
df

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Id
0,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,18.8,5,0
1,7.8,0.880,0.00,2.6,0.098,25.0,67.0,0.99680,3.20,0.68,19.6,5,1
2,7.8,0.760,0.04,2.3,0.092,15.0,54.0,0.99700,3.26,0.65,19.6,5,2
3,11.2,0.280,0.56,1.9,0.075,17.0,60.0,0.99800,3.16,0.58,19.6,6,3
4,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,18.8,5,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1138,6.3,0.510,0.13,2.3,0.076,29.0,40.0,0.99574,3.42,0.75,22.0,6,1592
1139,6.8,0.620,0.08,1.9,0.068,28.0,38.0,0.99651,3.42,0.82,19.0,6,1593
1140,6.2,0.600,0.08,2.0,0.090,32.0,44.0,0.99490,3.45,0.58,21.0,5,1594
1141,5.9,0.550,0.10,2.2,0.062,39.0,51.0,0.99512,3.52,0.76,22.4,6,1595
1142,5.9,0.645,0.12,2.0,0.075,32.0,44.0,0.99547,3.57,0.71,20.4,5,1597

In [17]:
def rating(quality):
    if quality>5:
        return "Good"
    else:
        return "Bad"


df['quality review']=df['quality'].apply(rating)
df.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Id,quality review
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,18.8,5,0,Bad
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,19.6,5,1,Bad
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,19.6,5,2,Bad
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,19.6,6,3,Good
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,18.8,5,4,Bad

In [21]:
df['quality_label']=df['quality'].map({3:'Very Bad',
                                       4:'Bad'
                                       ,5:'Good'
                                       ,6:"Very Good"
                                       ,7:"Nice"
                                       ,8:"Excellent"})

df['quality_label2']=df['quality_label'].map({
    "Good":'Good1',"Bad":"Bad2"
})
df.head(10)

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Id,quality review,quality_label,quality_label2
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,18.8,5,0,Bad,Good,Good1
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,19.6,5,1,Bad,Good,Good1
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,19.6,5,2,Bad,Good,Good1
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,19.6,6,3,Good,Very Good,NaN
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,18.8,5,4,Bad,Good,Good1
5,7.4,0.66,0.00,1.8,0.075,13.0,40.0,0.9978,3.51,0.56,18.8,5,5,Bad,Good,Good1
6,7.9,0.60,0.06,1.6,0.069,15.0,59.0,0.9964,3.30,0.46,18.8,5,6,Bad,Good,Good1
7,7.3,0.65,0.00,1.2,0.065,15.0,21.0,0.9946,3.39,0.47,20.0,7,7,Good,Nice,NaN
8,7.8,0.58,0.02,2.0,0.073,9.0,18.0,0.9968,3.36,0.57,19.0,7,8,Good,Nice,NaN
9,6.7,0.58,0.08,1.8,0.097,15.0,65.0,0.9959,3.28,0.54,18.4,5,10,Bad,Good,Good1

In [23]:
df['quality_replace']=df['quality_label'].replace({
    "Good":"Good1","Bad":"Bad1"
})

df.head(10)

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Id,quality review,quality_label,quality_label2,quality_replace
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,18.8,5,0,Bad,Good,Good1,Good1
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,19.6,5,1,Bad,Good,Good1,Good1
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,19.6,5,2,Bad,Good,Good1,Good1
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,19.6,6,3,Good,Very Good,NaN,Very Good
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,18.8,5,4,Bad,Good,Good1,Good1
5,7.4,0.66,0.00,1.8,0.075,13.0,40.0,0.9978,3.51,0.56,18.8,5,5,Bad,Good,Good1,Good1
6,7.9,0.60,0.06,1.6,0.069,15.0,59.0,0.9964,3.30,0.46,18.8,5,6,Bad,Good,Good1,Good1
7,7.3,0.65,0.00,1.2,0.065,15.0,21.0,0.9946,3.39,0.47,20.0,7,7,Good,Nice,NaN,Nice
8,7.8,0.58,0.02,2.0,0.073,9.0,18.0,0.9968,3.36,0.57,19.0,7,8,Good,Nice,NaN,Nice
9,6.7,0.58,0.08,1.8,0.097,15.0,65.0,0.9959,3.28,0.54,18.4,5,10,Bad,Good,Good1,Good1

In [26]:
df.rename(columns={"fixed acidity": "ACIDITY"}, inplace=True)
df.head()

,ACIDITY,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Id,quality review,quality_label,quality_label2,quality_replace
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,18.8,5,0,Bad,Good,Good1,Good1
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,19.6,5,1,Bad,Good,Good1,Good1
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,19.6,5,2,Bad,Good,Good1,Good1
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,19.6,6,3,Good,Very Good,NaN,Very Good
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,18.8,5,4,Bad,Good,Good1,Good1

In [18]:
df.to_csv("Wine_updated.csv",index=False)

#String Operation

In [29]:
df1=pd.read_csv("wine_data.csv")
df1.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Id,name,date
0,8.50,0.28,0.56,1.8,0.092,35.0,103.0,0.99690,3.30,0.75,10.50,7,16,WineA,2023-01-10
1,8.00,0.59,0.16,1.8,0.065,3.0,16.0,0.99620,3.42,0.92,10.50,7,128,WineB,2023-02-15
2,9.60,0.32,0.47,1.4,0.056,9.0,24.0,0.99695,3.22,0.82,10.30,7,200,WineC,2023-03-20
3,12.80,0.30,0.74,2.6,0.095,9.0,28.0,0.99940,3.20,0.77,10.80,7,205,WineD,2023-04-25
4,9.91,0.45,0.49,2.8,0.053,21.9,60.5,0.99683,3.31,0.90,8.88,4,5,Weingut Syrah Reserve 575,2023-02-12

In [30]:
df1.name.str.upper()

0                                WINEA
1                                WINEB
2                                WINEC
3                                WINED
4            WEINGUT SYRAH RESERVE 575
                    ...
215           BODEGA PINOT CLASSIC 513
216       CASTELLO MERLOT GRAND CRU 41
217    BODEGA CHARDONNAY GRAND CRU 257
218       CHATEAU CABERNET SPECIAL 857
219       BODEGA SAUVIGNON CLASSIC 591
Name: name, Length: 220, dtype: str

In [33]:
df1.name.str.capitalize()
df1.name.str.len()

0       5
1       5
2       5
3       5
4      25
       ..
215    24
216    28
217    31
218    28
219    28
Name: name, Length: 220, dtype: int64

In [36]:
df1[df1.name.str.contains("a")]

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Id,name,date
4,9.91,0.45,0.49,2.8,0.053,21.9,60.5,0.99683,3.31,0.90,8.88,4,5,Weingut Syrah Reserve 575,2023-02-12
5,8.72,0.56,0.34,0.8,0.059,22.3,59.8,0.99571,3.35,0.79,9.79,4,6,Bodega Riesling Special 559,2024-05-09
6,9.54,0.61,0.41,3.1,0.064,23.5,51.8,0.99716,3.32,0.73,9.15,4,7,Domaine Pinot Grand Cru 285,2022-01-14
7,9.08,0.63,0.49,1.1,0.072,18.1,42.5,0.99795,3.20,0.81,8.88,3,8,Domaine Riesling Premium 349,2023-07-24
8,8.88,0.44,0.40,2.9,0.079,15.3,43.6,0.99742,3.42,0.79,10.84,5,9,Domaine Cabernet Classic 105,2022-07-09
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
215,10.62,0.38,0.41,3.0,0.072,24.8,55.7,0.99732,3.16,0.79,10.99,6,216,Bodega Pinot Classic 513,2024-10-08
216,10.21,0.17,0.60,2.5,0.059,13.7,21.2,0.99388,3.21,0.72,11.25,7,217,Castello Merlot Grand Cru 41,2024-06-03
217,11.29,0.36,0.46,2.8,0.082,26.6,40.2,0.99651,3.27,0.84,11.24,7,218,Bodega Chardonnay Grand Cru 257,2022-02-22
218,9.21,0.36,0.51,2.6,0.082,10.3,19.6,0.99854,3.20,0.70,11.09,6,219,Chateau Cabernet Special 857,2022-02-12
219,10.02,0.21,0.47,1.8,0.050,17.2,33.5,0.99676,3.04,0.70,11.37,7,220,Bodega Sauvignon Classic 591,2022-03-24

In [59]:
df1['date']=pd.to_datetime(df1.date)
df1['Year']=df1.date.dt.year
df1.info()

<class 'pandas.DataFrame'>
RangeIndex: 220 entries, 0 to 219
Data columns (total 16 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   fixed acidity         220 non-null    float64
 1   volatile acidity      220 non-null    float64
 2   citric acid           220 non-null    float64
 3   residual sugar        220 non-null    float64
 4   chlorides             220 non-null    float64
 5   free sulfur dioxide   220 non-null    float64
 6   total sulfur dioxide  220 non-null    float64
 7   density               220 non-null    float64
 8   pH                    220 non-null    float64
 9   sulphates             220 non-null    float64
 10  alcohol               220 non-null    float64
 11  quality               220 non-null    int64
 12  Id                    220 non-null    int64
 13  name                  220 non-null    str
 14  date                  220 non-null    datetime64[us]
 15  Year                  220 non-null    int32
dtypes: datetime64[us](1), float64(11), int32(1), int64(2), str(1)
memory usage: 26.8 KB

In [72]:

df1.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Id
0,8.50,0.28,0.56,1.8,0.092,35.0,103.0,0.99690,3.30,0.75,10.50,7,16
1,8.00,0.59,0.16,1.8,0.065,3.0,16.0,0.99620,3.42,0.92,10.50,7,128
2,9.60,0.32,0.47,1.4,0.056,9.0,24.0,0.99695,3.22,0.82,10.30,7,200
3,12.80,0.30,0.74,2.6,0.095,9.0,28.0,0.99940,3.20,0.77,10.80,7,205
4,9.91,0.45,0.49,2.8,0.053,21.9,60.5,0.99683,3.31,0.90,8.88,4,5

In [73]:
df1['High_Alcohol']=df1.alcohol >=10
df1.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Id,High_Alcohol
0,8.50,0.28,0.56,1.8,0.092,35.0,103.0,0.99690,3.30,0.75,10.50,7,16,True
1,8.00,0.59,0.16,1.8,0.065,3.0,16.0,0.99620,3.42,0.92,10.50,7,128,True
2,9.60,0.32,0.47,1.4,0.056,9.0,24.0,0.99695,3.22,0.82,10.30,7,200,True
3,12.80,0.30,0.74,2.6,0.095,9.0,28.0,0.99940,3.20,0.77,10.80,7,205,True
4,9.91,0.45,0.49,2.8,0.053,21.9,60.5,0.99683,3.31,0.90,8.88,4,5,False

In [74]:
df1['Wine Type']='Red Wine'
df1.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Id,High_Alcohol,Wine Type
0,8.50,0.28,0.56,1.8,0.092,35.0,103.0,0.99690,3.30,0.75,10.50,7,16,True,Red Wine
1,8.00,0.59,0.16,1.8,0.065,3.0,16.0,0.99620,3.42,0.92,10.50,7,128,True,Red Wine
2,9.60,0.32,0.47,1.4,0.056,9.0,24.0,0.99695,3.22,0.82,10.30,7,200,True,Red Wine
3,12.80,0.30,0.74,2.6,0.095,9.0,28.0,0.99940,3.20,0.77,10.80,7,205,True,Red Wine
4,9.91,0.45,0.49,2.8,0.053,21.9,60.5,0.99683,3.31,0.90,8.88,4,5,False,Red Wine

In [85]:
import pandas as pd

data1 = {
    'Name':['A','B','C'],
    'age':[23,24,27],
    'salary':[3000,4000,5000]
}

data2 = {
    'Name': ['A','E','C'],
    'age': [23,32,27],
    'salary': [3000,7000,5000]
}

new_df1 = pd.DataFrame(data1)
new_df2 = pd.DataFrame(data2)

print(new_df1)
print(new_df2)

  Name  age  salary
0    A   23    3000
1    B   24    4000
2    C   27    5000
  Name  age  salary
0    A   23    3000
1    E   32    7000
2    C   27    5000

In [86]:
pd.concat([new_df1,new_df2],ignore_index=True,axis=1)

   0   1     2  3   4     5
0  A  23  3000  A  23  3000
1  B  24  4000  E  32  7000
2  C  27  5000  C  27  5000

In [89]:
#Merge

pd.merge(new_df1,new_df2,on='age',how='outer')

  Name_x  age  salary_x Name_y  salary_y
0      A   23    3000.0      A    3000.0
1      B   24    4000.0    NaN       NaN
2      C   27    5000.0      C    5000.0
3    NaN   32       NaN      E    7000.0